# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class RealtyspidersItem(scrapy.Item):
    BuildType = scrapy.Field()
    BuilderName = scrapy.Field()
    State = scrapy.Field()
    Region = scrapy.Field()
    DesignName = scrapy.Field()
    BuildFinishRange = scrapy.Field()
    BasePrice = scrapy.Field()
    Squares = scrapy.Field()
    HouseWidth = scrapy.Field()
    HouseLength = scrapy.Field()
    Lot_BlockWidth = scrapy.Field()
    LandSize = scrapy.Field()
    SturturalWarranty = scrapy.Field()
    EnergyRating = scrapy.Field()
    Storey = scrapy.Field()
    Bedrooms = scrapy.Field()
    Bathrooms = scrapy.Field()
    Garage = scrapy.Field()
    LivingArea = scrapy.Field()
    TheatreRoom_Yes_No = scrapy.Field()
    SeparateMeals_Yes_No = scrapy.Field()
    Alfresco_Yes_No = scrapy.Field()
    Study_Yes_No = scrapy.Field()
    WalkinPantry_Yes_No = scrapy.Field()
    BultersPantry_Yes_No = scrapy.Field()
    Void_Yes_No = scrapy.Field()
    His_HerWIR_Yes_No = scrapy.Field()
    BedroomGrFloor_Yes_No = scrapy.Field()
    SteelStructure_Yes_No = scrapy.Field()
    Balcony_Yes_No = scrapy.Field()
    LoungeDimension = scrapy.Field()
    FamilyDimension = scrapy.Field()
    Meals_DiningDimension = scrapy.Field()
    TheatreDimension = scrapy.Field()
    KitchenDimension = scrapy.Field()
    StudyDimension = scrapy.Field()
    AlfrescoDimension = scrapy.Field()
    GarageDimension = scrapy.Field()
    MasterBedroomDimension = scrapy.Field()
    Bedroom2Dimension = scrapy.Field()
    Bedroom3Dimension = scrapy.Field()
    Bedroom4Dimension = scrapy.Field()
    KitchenAppliance = scrapy.Field()
    KitchenAppliance1 = scrapy.Field()
    KitchenAppliance2 = scrapy.Field()
    KitchenAppliance3 = scrapy.Field()
    ApplianceBrand = scrapy.Field()
    KitchenBenchtop = scrapy.Field()
    Splashback = scrapy.Field()
    Windows = scrapy.Field()
    FloorCovering = scrapy.Field()
    FloorCovering1 = scrapy.Field()
    FloorCovering2 = scrapy.Field()
    Cooling = scrapy.Field()
    CeilingHeight = scrapy.Field()
    Bath = scrapy.Field()
    EnsuiteWallTiling = scrapy.Field()
    EnsuiteBenchtop = scrapy.Field()
    EnsuiteShowerbase = scrapy.Field()
    WallPaint = scrapy.Field()
    WIRFitouts = scrapy.Field()
    SecuritySystem = scrapy.Field()
    Downlights = scrapy.Field()
    Landscaping = scrapy.Field()
    Driveway = scrapy.Field()
    Promotion = scrapy.Field()
    OtherInclusions = scrapy.Field()
    OtherInclusions1 = scrapy.Field()
    OtherInclusions2 = scrapy.Field()
    OtherInclusions3 = scrapy.Field()
    OtherInclusions4 = scrapy.Field()
    OtherInclusions5 = scrapy.Field()
    BuilderEmailAddress = scrapy.Field()
    DisplayLocation = scrapy.Field()
    Lot_BlockAddress = scrapy.Field()
    HomeDesignMainImage = scrapy.Field()
    FloorPlanImage1 = scrapy.Field()
    FloorPlanImage2 = scrapy.Field()
    BrochureImage_pdf = scrapy.Field()
    InclusionsImage_pdf = scrapy.Field()
    Image1 = scrapy.Field()
    Image2 = scrapy.Field()
    Image3 = scrapy.Field()
    Image4 = scrapy.Field()
    Image5 = scrapy.Field()
    Image6 = scrapy.Field()
    Image7 = scrapy.Field()
    Image8 = scrapy.Field()
    Image9 = scrapy.Field()
    Image10 = scrapy.Field()
    Image11 = scrapy.Field()
    Image12 = scrapy.Field()
    Image13 = scrapy.Field()
    Image14 = scrapy.Field()
    Image15 = scrapy.Field()
